reviewers:
  # The default reviewers
  defaults:
    - core-reviewers # group

  # Reviewer groups each of which has a list of GitHub usernames
  groups:
    core-reviewers:
      - team:ui # GitHub team

options:
  number_of_reviewers: 2
