name: 'Add designer to review'
on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  add-designer:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          repo-token: ${{ secrets.token }}
          configuration-path: '.github/add_designer_to_review.yml'
