name: 'Chromatic'

on:
  pull_request:
    branches: [main, next]
    paths-ignore:
      - packages/ui/**
      - packages/icons/**
      - packages/fonts/**
      - packages/components/**
      - packages/form/**
      - packages/validations/**
      - .storybook/**
      - package.json
      - package-lock.json

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No chromatic-deployment required"'
