name: telegram message
on:
  pull_request:
    branches:
    - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: -643866976
          token: 5296240564:AAEStLQPL35cJ7cN8OPyYfA6kg2rG7_Vkns
          message: |
            ${{ github.actor }} created PR:
            Title: ${{ github.event.pull_request.title }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
