name: pull request approved notification
on:
  pull_request_review:
    types: [submitted]
    branches:
    - main

jobs:
  fetch:
    name: fetch
    if: github.event.review.state == 'approved'
    uses: kaluga-astral/frontend/.github/workflows/fetch_pr_info.yml@main
    with:
      pr_url: ${{ github.event.pull_request.url }}

  notify:
    name: notify
    needs: fetch
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on PR
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            &#9989;&#9989;&#9989;
            ${{ github.event.sender.login }} аппрувнул PR от ${{ fromJSON(needs.fetch.outputs.result).user.login }}

            ${{ fromJSON(needs.fetch.outputs.result).title }}

            ${{ fromJSON(needs.fetch.outputs.result).html_url }}
