name: "Reviewer lottery"
on:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: uesteibar/reviewer-lottery@v2
      with:
        repo-token: ${{ secrets.AUTO_REVIEWERS_TOKEN }}
